// <auto-generated />
using ASPTestAPIUdemy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASPTestAPIUdemy.Migrations
{
    [DbContext(typeof(HotelListingDbContext))]
    [Migration("20230209222847_NewCollectionType")]
    partial class NewCollectionType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASPTestAPIUdemy.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Canada",
                            ShortName = "CA"
                        },
                        new
                        {
                            Id = 2,
                            Name = "USA",
                            ShortName = "US"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mexico",
                            ShortName = "MX"
                        });
                });

            modelBuilder.Entity("ASPTestAPIUdemy.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "1 street mcgill",
                            CountryId = 1,
                            Name = "Hotel n1",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "2 street JFK",
                            CountryId = 2,
                            Name = "Hotel n2",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 3,
                            Adresse = "3 Street Gumbo",
                            CountryId = 3,
                            Name = "Hotel n3",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 4,
                            Adresse = "1 Street Greatest",
                            CountryId = 1,
                            Name = "The best hotel",
                            Rating = 4.2000000000000002
                        });
                });

            modelBuilder.Entity("ASPTestAPIUdemy.Data.Hotel", b =>
                {
                    b.HasOne("ASPTestAPIUdemy.Data.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ASPTestAPIUdemy.Data.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
